
###
GET http://localhost:8080/api/socks?color=re&operation=equal&cottonPart=1000

###

POST http://localhost:8080/api/socks/income
Content-Type: application/json

{
  "color": "black",
  "cottonPart": 1000,
  "quantity":  50
}

###

POST http://localhost:8080/api/socks/outcome
Content-Type: application/json

{
  "color": "black",
  "cottonPart": 100,
  "quantity":  90
}



