
###
GET http://localhost:8080/api/socks?color=red&operation=equal&cottonPart=55

###

POST http://localhost:8080/api/socks/income
Content-Type: application/json

{
  "color": "yellow",
  "cottonPart": 80,
  "quantity":  50
}

###

POST http://localhost:8080/api/socks/outcome
Content-Type: application/json

{
  "color": "yellow",
  "cottonPart": 80,
  "quantity":  100
}



